### PR TITLE
Use unicode string for log response

### PR DESCRIPTION
**Pull request by ghost**
The current python_bayeux implementation fail if response contain unicode characters. It is only a string formatting issue.

This PR update the logging call to avoid problems.

### CODE REVIEW

**Comment by ghost** [comment]
ping @adamlincoln : did you have time to look thid PR ? Can I made some other change to help you ?

**Comment by adamlincoln** [comment]
@christophe-gabard good catch, thank you for the PR!

**Comment by ghost** [comment]
Thank you ! Do you plan to push a release update on Pypi ? We need this patch for your other project  https://github.com/SalesforceFoundation/salesforce-streaming-client and, without release, we need to use a github-hosted dependency.

**Comment by adamlincoln** [comment]
@christophe-gabard done!

https://pypi.python.org/pypi/python-bayeux/0.1.2

**Comment by ghost** [comment]
Thank you !

**Pull request merged**
